services:
  app:
    image: serversideup/php:8.4-fpm-nginx
    container_name: finalweb_backend
    environment:
      - PHP_DISPLAY_ERRORS=1
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=sail
      - DB_PASSWORD=password
      - REDIS_HOST=redis
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8080"
      - "8085:8085"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: finalweb_frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: finalweb_db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=sail
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: finalweb_redis
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
